### ISSUE TITLE
Crazy Q

### ISSUE THREAD

**Issue by mexicantexan** [stephenbradshaw/hlextend#1]
Still trying to wrap my head around this, so apologies in advance and I appreciate anything you can toss my way! But I had 3 questions for you. 

1. If I wanted to hash "hello" with your script, how would I call that?
2. Can your script then return the original text if I have the hashed key from (1) and the length of the text? So can I get back to 'hello'?
3. If two is yes, how would you suggest going about it?

**Comment by stephenbradshaw** [comment]
1. You don't really want to use this to hash a known value, but you can...

    In [1]: import hlextend
    In [2]: sha = hlextend.new('sha1')
    In [3]: sha.hash('hello')
    In [4]: sha.hexdigest()
    Out[4]: 'aaf4c61ddcc5e8a2dabede0f3b482cd9aea9434d'

2. No. This is not the way hash length extension attacks work. They essentially allow you to append extra data to an existing hash where you only know some details about the input, not reverse the hashing algorithm completely.

You may want to read [this](http://www.thegreycorner.com/2014/08/hlextend-pure-python-hash-length.html), which gives a practical example of attacking a web application that has a hash length extension vulnerability.
