### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by shawnlsj97** [stephenbradshaw/hlextend#3]
Traceback (most recent call last):
  File "hasher.py", line 5, in <module>
    data = sha.extend('O:6:"Hacker":2:{s:17:" Hacker show_flag";b:1;s:16:" Hacker username";s:10:"hacker1337";}', 'O:6:"Hacker":2:{s:17:" Hacker show_flag";b:0;s:16:" Hacker username";s:10:"hacker1337";}', 8, '367f4643e26f0820db070629f43a5e6a614d778a5f1fd68d1fe1ce2d00b3934d')
  File "C:\Users\Shawn Lee\Downloads\hlextend-master\hlextend-master\hlextend.py", line 118, in extend
    self.__setStartingHash(startHash)
  File "C:\Users\Shawn Lee\Downloads\hlextend-master\hlextend-master\hlextend.py", line 154, in __setStartingHash
    hashVals = [ int(startHash[a:a+self._b1],base=16) for a in range(0,len(startHash), self._b1) ]
TypeError: 'float' object cannot be interpreted as an integer

**Comment by p3n7a90n** [comment]
Hi, I got the same error, I debugged it and self._b1 data type is **float**. you can do the type conversion as mentioned below.        
hashVals = [ int(startHash[a:a+int(self._b1)],base=16) for a in range(0,len(startHash), int(self._b1)) ]
