### ISSUE TITLE
Bytestring return

### ISSUE THREAD

**Issue by Iaotle** [stephenbradshaw/hlextend#7]
It would be much more convenient to have the return type be a bytestring. This way we won't have to unescape the extra bytes that are added when padding.

In my code I had to do
```python3
extended_query = sha.extend('&filename=' + HIDDEN_FILE, file_query, KEY_SIZE, MAC)
extended_query = bytes(extended_query, 'utf-8').decode("unicode_escape") # unescape bytes
forged_filename = urllib.parse.quote(extended_query, safe='?&=').replace('%C2', '') # conver to url remove garbage %C2
querystring = '?' + forged_filename + '&mac=' + forged_mac # create query
```

**Comment by stephenbradshaw** [comment]
Agreed. This was probably just a holdover from Python 2. Happy to accept another PR if you want to provide, otherwise I'll probably get to at at some point...

**Comment by Iaotle** [comment]
Sorry I'm not really into python that much, so I think I'll leave it to you :)

**Comment by stephenbradshaw** [comment]
Think this is fixed now
